# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/projects'),
        ),
    ]
